### PR TITLE
Fix build-tools (part of the Bottles runtime fix effort)

### PR DESCRIPTION
**Pull request by koplo199**
Part of the Bottles runtime fix effort, see https://github.com/bottlesdevs/Bottles/issues/3054.

This PR is needed by (and blocks):
- https://github.com/bottlesdevs/runtime/pull/7

This PR is blocked by:
- https://github.com/mirkobrombin/runtimezilla/pull/3

Marking as draft as a result, but technically ready for review.

### CODE REVIEW

**Comment by koplo199** [comment]
I've decided against updating the `recipe.yml` packages in this PR. The reason is that it may need another update soon, so better wait until that moment.

On a side note, @mirkobrombin (sorry to tag you directly) do you remember how this package list was originally chosen? It would be great to add a `README` stating it, in order to make it easier to maintain them.

For instance if they were chosen after analyzing  say [libwine](https://packages.debian.org/bookworm/libwine) dependencies, reconstucting them would be far more easier to do as it will only require doing the same analyze on the new distribution update or the new platform.

This analyse could even be automated, making it even easier to maintain! It would require updating `runtimezilla` to support such use case though.

**Comment by mirkobrombin** [comment]
I do not remember, it was some years ago. I think basing the analysis on libwine actually makes sense

**Comment by koplo199** [comment]
Ok, I'll add that to a `runtime/README` file.

**Comment by koplo199** [comment]
Done : https://github.com/bottlesdevs/runtime/pull/7/commits/d6f449aa6ff71aec33b185516670a0086995be41

**Pull request merged**
